# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
     - main

jobs:

  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: Tinesh379
        server-password: ACCESS_TOKEN
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - id: tag_id
      name: Bump Version and Tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: false
        DRY_RUN: true

    - name: Change pom version
      run: mvn versions:set -DnewVersion=${{ steps.tag_id.outputs.new_tag}} #override project pom version

    - name: Build with Maven
      run: mvn -B package --file pom.xml 

    - name: Publish to GitHub Packages Apache Maven
      run: mvn clean deploy -s $GITHUB_WORKSPACE/settings.xml  
      env:
        ACCESS_TOKEN: ${{ github.token }}
    outputs:
        version: ${{ steps.tag_id.outputs.new_tag}} #stores the tag but does not tag the repo.

  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v2
    - name: Create a Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ needs.Build.outputs.version}}
        release_name: Release-${{ needs.Build.outputs.version}}
    
    
