# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branch: [main]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: Tinesh379
        server-password: ACCESS_TOKEN
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Bump Version and Tag
      id: release_tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        RELEASE_BRANCHES: main
        ACCESS_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        WITH_V: true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        ACCESS_TOKEN: ${{ github.token }}
