# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branch: [main]
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: Tinesh379
        server-password: ACCESS_TOKEN
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Bump Version and Tag
      id: tag_id
      uses: anothrNick/github-tag-action@1.36.0
      env:
        RELEASE_BRANCHES: main
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: false
        VESRION: ${{ steps.tag_id.outputs.new_tag}}
    - name: change pom version
      run: mvn versions:set -DnewVersion=$VESRION

    - name: Build with Maven
      run: mvn -B package --file pom.xml 

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --Dversion= ${{ steps.tag_id.outputs.new_tag }}
      env:
        ACCESS_TOKEN: ${{ github.token }}
  release-project:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: Release-${{ github.run_number }}
        
